//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public direccion()
        {
            this.propiedad = new HashSet<propiedad>();
        }
    
        public int iddireccion { get; set; }
        public string calle { get; set; }
        public string cruzamiento1 { get; set; }
        public string cruzamiento2 { get; set; }
        public string noExterior { get; set; }
        public string localidad { get; set; }
        public string entidadFed { get; set; }
        public int cp { get; set; }
        public string ubicacion { get; set; }
        public string auxiliar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<propiedad> propiedad { get; set; }
    }
}
