//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagen
    {
        public int idimage { get; set; }
        public byte[] imagen1 { get; set; }
        public byte[] imagen11 { get; set; }
        public byte[] imagen2 { get; set; }
        public byte[] imagen3 { get; set; }
        public Nullable<int> idpropiedad { get; set; }
        public string auxiliar { get; set; }
    
        public virtual propiedad propiedad { get; set; }
    }
}
