//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        public int idmensaje { get; set; }
        public string mensaje1 { get; set; }
        public int idpropiedad { get; set; }
        public Nullable<int> idEmisor { get; set; }
        public Nullable<int> idReceptor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string status { get; set; }
        public string auxiliar { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
