//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasosWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbhomemxEntities2 : DbContext
    {
        public dbhomemxEntities2()
            : base("name=dbhomemxEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<direccion> direccion { get; set; }
        public virtual DbSet<imagen> imagen { get; set; }
        public virtual DbSet<mensaje> mensaje { get; set; }
        public virtual DbSet<propiedad> propiedad { get; set; }
        public virtual DbSet<renta> renta { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
