//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicios()
        {
            this.propiedad = new HashSet<propiedad>();
        }
    
        public int idservicios { get; set; }
        public Nullable<bool> internet { get; set; }
        public Nullable<bool> comida { get; set; }
        public Nullable<bool> limpieza { get; set; }
        public Nullable<bool> amueblada { get; set; }
        public Nullable<bool> parking { get; set; }
        public Nullable<bool> alberca { get; set; }
        public Nullable<bool> clima { get; set; }
        public Nullable<bool> terraza { get; set; }
        public Nullable<bool> lavanderia { get; set; }
        public string auxiliar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<propiedad> propiedad { get; set; }
    }
}
